# Generated by Django 4.2.2 on 2023-06-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('creatinine_phosphokinase', models.IntegerField(default=0)),
                ('ejection_fraction', models.IntegerField(default=0)),
                ('platelets', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('death_event', models.IntegerField(blank=True, default=0)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Результаты анализов',
            },
        ),
    ]
